services:
  - type: web
    name: dart-pi-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --graceful-timeout 30 app:app
    autoDeploy: true
